# Generated by Django 2.2 on 2022-03-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220301_1821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_model',
        ),
    ]
